version = [0, 0, 1]
kind = 'exe'

[external.SDL]
lib_names = 'libSDL2.so'
include_paths = '/usr/include/SDL2'


[test.use.Meliorate]
as = 'shared'

[test.external.Snowhouse]
include_paths = '/home/david/Projects/3rdParty/snowhouse'

