projectRoot = "../.."

cxx = "clang++"
cc = "clang"
ar = "ar"
compilerFrontend="osx"

flags = [
    "-std=c++2a",
    "-O1",
    "-g",
    "-fsanitize=address",
    "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    "-fsanitize=undefined"
]

defines = ["-DSPDLOG_COMPILED_LIB", "-DSPDLOG_FMT_EXTERNAL"]

[[builds]]
    name = "spdlog"
    buildRule = "staticlib"
    requires = ["fmt"]
    outputName = "spdlog"
    srcDirs = ["lib/spdlog/src"]
    includePaths = ["lib/spdlog/include", "lib/fmt/include"]

[[builds]]
    name = "fmt"
    buildRule = "staticlib"
    outputName = "fmt"
    srcDirs = ["lib/fmt/src"]
    includePaths = ["lib/fmt/include"]

[[builds]]
    name = "imgui"
    buildRule = "staticlib"
    outputName = "imgui"
    srcDirs = ["lib/imgui"]
    includePaths = ["lib/imgui"]

[[builds]]
    name = "untitled2d"
    buildRule = "exe"
    requires = ["spdlog", "fmt"]
    outputName = "untitled2d"
    srcDirs = ["src"]
    includePaths = [
        "/usr/local/include/SDL2",
        "include",
    ]
    libraries = ["SDL2"]


[[builds]]
    name = "test"
    buildRule = "exe"
    requires = []
    outputName = "Tests"
    srcDirs = ["test"]
    includePaths = [
        "/usr/local/include/SDL2",
        "include",
    ]
    libraries = ["SDL2"]
