projectRoot = "../.."

cxx = "clang++"
cc = "clang"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-g"
]

defines = []

# [[builds]]                              # a list of builds.
#     name = "lib_calculator"             # the unique name for this build.
#     buildRule = "staticlib"             # the type of build, in this case create a static library.
#     outputName = "libCalculator.a"      # the library output name,
#     srcDirs = ["lib"]                   # the src directories  to build the static library from.
#     includePaths = ["include"]    # additional include paths to use during the build.

#[[builds]]
#    name = "lib_calculator_so"         # the unique name for this build.
#    buildRule = "dynamiclib"           # the type of build, in this case create a shared library.
#    outputName = "libCalculator.so"    # the library output name,
#    srcDirs = ["lib"]                  # the src directories to build the shared library from.
#    includePaths = ["include"]         # additional include paths to use during the build.

[[builds]]
    name = "shapeAttack"
    buildRule = "exe"
    outputName = "ShapeAttack"
    srcDirs = ["src"]
    includePaths = [
        "/usr/include/SDL2",
        "include",
        "lib/LinAlg/include"
    ]
    libraries = ["SDL2"]


[[builds]]
    name = "test"
    buildRule = "exe"
    outputName = "Tests"
    srcDirs = ["test"]
    includePaths = [
        "/usr/include/SDL2",
        "include",
        "lib/Meliorate/include",
        "lib/LinAlg/include"
    ]
    libraries = ["SDL2"]