projectRoot = "../.."

cxx = "clang++"
cc = "clang"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O1",
    "-g"
]

defines = ["-DSPDLOG_FMT_EXTERNAL"]

[[builds]]
    name = "fmt"
    buildRule = "staticlib"
    outputName = "fmt"
    srcDirs = ["lib/fmt/src"]
    includePaths = ["lib/fmt/include"]


[[builds]]
    name = "spdlog"
    defines = ["-DSPDLOG_COMPILED_LIB"]
    buildRule = "staticlib"
    requires = ["fmt"]
    outputName = "spdlog"
    srcDirs = ["lib/spdlog/src"]
    includePaths = ["lib/spdlog/include"]


[[builds]]
    name = "imgui"
    buildRule = "staticlib"
    outputName = "imgui"
    srcDirs = ["lib/imgui"]
    includePaths = ["lib/imgui"]


[[builds]]
    name = "shapeAttack"
    buildRule = "exe"
    flags = [
        "-fsanitize=address",
        "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
        "-fsanitize=undefined"
    ]
    requires = ["fmt", "spdlog", "imgui"]
    outputName = "ShapeAttack"
    srcDirs = ["src"]
    includePaths = [
        "/usr/include/SDL2",
        "include",
        "lib/LinAlg/include"
    ]
    libraries = ["SDL2"]


[[builds]]
    name = "test"
    buildRule = "exe"
    flags = [
        "-fsanitize=address",
        "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
        "-fsanitize=undefined"
    ]
    requires = ["fmt", "spdlog"]
    outputName = "Tests"
    srcDirs = ["test"]
    includePaths = [
        "/usr/include/SDL2",
        "include",
        "lib/Meliorate/include",
        "lib/LinAlg/include"
    ]
    libraries = ["SDL2"]