projectRoot = "../.."

cxx = "clang++"
cc = "clang"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O1",
    "-g",
    # "-Wall"
]

defines = ["-DSPDLOG_FMT_EXTERNAL"]

[[builds]]
    name = "fmt"
    buildRule = "staticlib"
    outputName = "fmt"
    srcDirs = ["lib/fmt/src"]
    includePaths = ["lib/fmt/include"]


[[builds]]
    name = "spdlog"
    defines = ["-DSPDLOG_COMPILED_LIB"]
    buildRule = "staticlib"
    requires = ["fmt"]
    outputName = "spdlog"
    srcDirs = ["lib/spdlog/src"]
    includePaths = ["lib/spdlog/include"]


[[builds]]
    name = "imgui"
    defines = ["-DIMGUI_IMPL_OPENGL_LOADER_GL3W"]
    buildRule = "staticlib"
    outputName = "imgui"
    srcDirs = [
        "lib/imgui/examples/imgui_impl_sdl.cpp",
        "lib/imgui/examples/imgui_impl_opengl3.cpp",
        "lib/imgui/imgui.cpp",
        "lib/imgui/imgui_demo.cpp",
        "lib/imgui/imgui_draw.cpp",
        "lib/imgui/imgui_widgets.cpp",
        "lib/imgui/examples/libs/gl3w/GL/gl3w.c",
    ]
    includePaths = [
        "/usr/include",
        "/usr/include/SDL2",
        "lib/imgui",
        "lib/imgui/examples/libs/gl3w",
        "lib/imgui/examples"
    ]


[[builds]]
    name = "kissSDL"
    defines = ["-DRESDIR=\\\"/home/dwalker0044/Projects/ShapeAttack/lib/kiss_sdl/\\\""]
    buildRule = "staticlib"
    outputName = "kiss_sdl"
    srcDirs = [
        "lib/kiss_sdl/kiss_draw.c",
        "lib/kiss_sdl/kiss_general.c",
        "lib/kiss_sdl/kiss_posix.c",
        "lib/kiss_sdl/kiss_widgets.c"
    ]
    includePaths = [
        "/usr/include",
        "/usr/include/SDL2",
        "lib/kiss_sdl"
    ]


[[builds]]
    name = "shapeAttack"
    buildRule = "exe"
    defines = ["-DRESDIR=\\\"/home/dwalker0044/Projects/ShapeAttack/lib/kiss_sdl/\\\""]
    # flags = [
    #     "-fsanitize=address",
    #     "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
    #     "-fsanitize=undefined",
    # ]
    # requires = ["fmt", "spdlog", "imgui"]
    requires = ["kissSDL"]
    outputName = "ShapeAttack"
    srcDirs = ["src"]
    includePaths = [
        "/usr/include",
        "/usr/include/SDL2",
        "include",
        "lib/LinAlg/include",
        "lib/fmt/include",
        "lib/spdlog/include"
    ]
    libraryPaths = [
        "builds/linux-clang++-debug/fmt",
        "builds/linux-clang++-debug/spdlog",
        "builds/linux-clang++-debug/imgui"
    ]
    libraries = ["SDL2_image", "SDL2_ttf", "SDL2", "fmt", "spdlog"]


[[builds]]
    name = "test"
    buildRule = "exe"
    flags = [
        "-fsanitize=address",
        "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
        "-fsanitize=undefined"
    ]
    # requires = ["fmt", "spdlog"]
    outputName = "Tests"
    srcDirs = ["test"]
    includePaths = [
        "/usr/include/SDL2",
        "include",
        "lib/Meliorate/include",
        "lib/LinAlg/include",
        "lib/fmt/include",
        "lib/spdlog/include",
        "lib/imgui",
    ]
    libraryPaths = [
        "builds/linux-clang++-debug/fmt",
        "builds/linux-clang++-debug/spdlog",
        "builds/linux-clang++-debug/imgui"
    ]
    libraries = ["SDL2", "fmt", "spdlog", "imgui"]