projectRoot = "../.."

cxx = "clang++"
cc = "clang"
ar = "ar"
compilerFrontend="gcc"

flags = [
    "-std=c++20",
    "-O0",
    "-g",
    # "-Wall"
]

defines = ["-DSPDLOG_FMT_EXTERNAL"]

[[builds]]
    name = "fmt"
    buildRule = "staticlib"
    outputName = "fmt"
    srcDirs = ["lib/fmt/src"]
    includePaths = ["lib/fmt/include"]


[[builds]]
    name = "spdlog"
    defines = ["-DSPDLOG_COMPILED_LIB"]
    buildRule = "staticlib"
    requires = ["fmt"]
    outputName = "spdlog"
    srcDirs = ["lib/spdlog/src"]
    includePaths = ["lib/spdlog/include"]


[[builds]]
    name = "kissSDL"
    defines = ["-DRESDIR=\\\"/home/dwalker0044/Projects/Untitled2D/lib/kiss_sdl/\\\""]
    buildRule = "staticlib"
    outputName = "kiss_sdl"
    srcDirs = [
        "lib/kiss_sdl/kiss_draw.c",
        "lib/kiss_sdl/kiss_general.c",
        "lib/kiss_sdl/kiss_posix.c",
        "lib/kiss_sdl/kiss_widgets.c"
    ]
    includePaths = [
        "/usr/include",
        "/usr/include/SDL2",
        "lib/kiss_sdl"
    ]


[[builds]]
    name = "untitled2d"
    buildRule = "exe"
    defines = ["-DRESDIR=\\\"/home/dwalker0044/Projects/Untitled2D/lib/kiss_sdl/\\\""]
    flags = [
        "-fsanitize=address",
        "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
        "-fsanitize=undefined",
    ]
    # requires = ["fmt", "spdlog", "imgui"]
    requires = ["kissSDL"]
    outputName = "Untitled2D"
    srcDirs = ["src", "src/collision", "src/drawing"]
    includePaths = [
        "/usr/include",
        "/usr/include/SDL2",
        "include",
        "lib/LinAlg/include",
        "lib/fmt/include",
        "lib/spdlog/include",
        "lib/msgpack-c/include"
    ]
    libraryPaths = [
        "builds/linux-clang++-debug/fmt",
        "builds/linux-clang++-debug/spdlog",
    ]
    libraries = ["SDL2_image", "SDL2_ttf", "SDL2", "fmt", "spdlog"]


[[builds]]
    name = "test"
    defines = ["-DTEST_EASING"]
    buildRule = "exe"
    flags = [
        "-fsanitize=address",
        "-fno-omit-frame-pointer", # get nicer stack traces from address sanitizer.
        "-fsanitize=undefined"
    ]
    requires = ["fmt"]
    outputName = "Tests"
    srcDirs = ["test"]
    includePaths = [
        "include",
        "lib/Meliorate/include",
        "lib/LinAlg/include",
        "lib/fmt/include",
    ]
