#pragma once

constexpr const int SERIALISATION_ERRORS = -500;
constexpr const int SERIALISATION_FAILED_TO_OPEN_SAVE_FILE = SERIALISATION_ERRORS - 1;
constexpr const int SERIALISATION_FAILED_TO_OPEN_LOAD_FILE = SERIALISATION_ERRORS - 2;